train_dataset_name: "./data/train_dataset_yzt.csv"
test_dataset_name: "./data/test_dataset_yzt.csv"
test_label_name: "./data/test_label_yzt.csv"

answer_label_name: "./answer/yzt_model_with_labels.csv"
model_name: "./save_models/model_yzt.pt"
answer_csv_name: "./answer/yzt_1_model.csv"

label: 4

wandb: False
name: "PatchTST_action_yzt"
