train_dataset_name: "./dataset/action-im/train_dataset_lyh_im.csv"
test_dataset_name: "./dataset/action-im/test_dataset_lyh_im.csv"
test_label_name: "./dataset/action-im/test_label_lyh_im.csv"

answer_label_name: "./answer/lyh_2_model_with_labels.csv"
model_name: "./save_models/model_lyh_2.pt"
answer_csv_name: "./answer/lyh_2_model.csv"

label: 5

wandb: True
name: "LSTM_action-im_lyh_im"