train_dataset_name: "./dataset/action-im/train_dataset_yzt_im.csv"
test_dataset_name: "./dataset/action-im/test_dataset_yzt_im.csv"
test_label_name: "./dataset/action-im/test_label_yzt_im.csv"

answer_label_name: "./answer/yzt_im_model_with_labels.csv"
model_name: "./save_models/model_yzt_im.pt"
answer_csv_name: "./answer/yzt_im_1_model.csv"

label: 5

wandb: True
name: "LSTM_action-im_yzt_im"