train_dataset_name: "./dataset/action-im/train_dataset_zxy_im2.csv"
test_dataset_name: "./dataset/action-im/test_dataset_zxy_im2.csv"
test_label_name: "./dataset/action-im/test_label_zxy_im2.csv"

answer_label_name: "./answer/zxy2_model_with_labels.csv"
model_name: "./save_models/model_zxy2.pt"
answer_csv_name: "./answer/zxy2_model.csv"

label: 5

wandb: True
name: "GPT2_action-im_zxy_2"