train_dataset_name: "./dataset/action/train_dataset_yzt.csv"
test_dataset_name: "./dataset/action/test_dataset_yzt.csv"
test_label_name: "./dataset/action/test_label_yzt.csv"
zero_test: "./dataset/action/test_dataset_yzt_0815.csv"

answer_label_name: "./answer/yzt_model_with_labels.csv"
model_name: "./save_models/model_yzt.pt"
answer_csv_name: "./answer/yzt_1_model.csv"

label: 4

wandb: True
name: "LSTM_action_yzt"