train_dataset_name: "./data/train_1.csv"
test_dataset_name: "./data/test_1.csv"
test_label_name: "./data/testA_1.csv"

answer_label_name: "./answer/zxy_model_with_labels.csv"
model_name: "./save_models/model_zxy.pt"
answer_csv_name: "./answer/zxy_model.csv"

label: 3

wandb: True
name: "GPT2_action_zxy"