train_dataset_name: "./dataset/hospital/train_total_im-patient.csv"
test_dataset_name: "./dataset/hospital/test_dataset_total_im-patient.csv"
test_label_name: "./dataset/hospital/test_label_total_im-patient.csv"

answer_label_name: "./answer/hospital_model_with_labels.csv"
model_name: "./save_models/model_hospital.pt"
answer_csv_name: "./answer/hospital_model.csv"

label: 4

wandb: True
name: "LSTM_hospital"