train_dataset_name: "./dataset/action/train_dataset_yzt_0815.csv"
test_dataset_name: "./dataset/action/test_dataset_yzt_0815.csv"
test_label_name: "./dataset/action/test_label_yzt_0815.csv"

answer_label_name: "./answer/yzt_0815_model_with_labels.csv"
model_name: "./save_models/model_yzt_0815.pt"
answer_csv_name: "./answer/yzt_0815_model.csv"

label: 4

wandb: True
name: "GPT2_action_yzt_0815"