train_dataset_name: "./dataset/pro/train_dataset_pro5.csv"
test_dataset_name: "./dataset/pro/test_dataset_pro5.csv"
test_label_name: "./dataset/pro/test_label_pro5.csv"

answer_label_name: "./answer/pro5_model_with_labels.csv"
model_name: "./save_models/model_pro5.pt"
answer_csv_name: "./answer/pro5_model.csv"

label: 5

wandb: False
name: "GPT2_pro_2"